# Generated by Django 3.2.12 on 2022-03-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Администратор'), (2, 'Модератор'), (3, 'Пользователь')], default=3, verbose_name='Роль'),
        ),
    ]
