# Generated by Django 3.2.12 on 2022-04-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/news_photos/', verbose_name='Новостное изображение'),
        ),
    ]
