# Generated by Django 3.2.12 on 2022-05-07 00:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habruser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 9, 0, 54, 28, 941991, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='habruser',
            name='role',
            field=models.CharField(choices=[('A', 'Администратор'), ('M', 'Модератор'), ('U', 'Зарегистрированный пользователь')], default='U', max_length=1, verbose_name='роль'),
        ),
    ]
