# Generated by Django 3.2.12 on 2022-04-05 15:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20220405_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='habrprofile',
            name='nik',
            field=models.CharField(blank=True, max_length=50, verbose_name='ник'),
        ),
        migrations.AlterField(
            model_name='habrprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('W', 'Ж')], max_length=1, verbose_name='пол'),
        ),
        migrations.AlterField(
            model_name='habruser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 7, 15, 4, 53, 377104, tzinfo=utc)),
        ),
    ]
