# Generated by Django 3.2.12 on 2022-04-20 14:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20220420_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habruser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 14, 20, 45, 424699, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='habruser',
            name='role',
            field=models.CharField(choices=[('A', 'Администратор'), ('U', 'Зарегистрированный пользователь'), ('M', 'Модератор')], default='U', max_length=1, verbose_name='роль'),
        ),
    ]
