# Generated by Django 3.2.12 on 2022-04-06 12:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20220405_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='habrprofile',
            name='zone',
            field=models.IntegerField(default=0, verbose_name='часовая зона'),
        ),
        migrations.AlterField(
            model_name='habrprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('W', 'Ж'), ('M', 'M')], max_length=1, verbose_name='пол'),
        ),
        migrations.AlterField(
            model_name='habruser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 8, 12, 18, 10, 260148, tzinfo=utc)),
        ),
    ]
