# Generated by Django 3.2.12 on 2022-04-17 16:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20220417_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habruser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 16, 10, 16, 712475, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='habruser',
            name='role',
            field=models.CharField(choices=[('M', 'Модератор'), ('U', 'Зарегистрированный пользователь'), ('A', 'Администратор')], default='U', max_length=1, verbose_name='роль'),
        ),
    ]
