# Generated by Django 3.2.12 on 2022-04-11 10:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_auto_20220409_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habrprofile',
            options={'verbose_name': 'профиль пользователя', 'verbose_name_plural': 'профили пользователей'},
        ),
        migrations.AddField(
            model_name='habrprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Статус активности'),
        ),
        migrations.AlterField(
            model_name='habruser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 13, 10, 32, 18, 939231, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='habruser',
            name='role',
            field=models.CharField(choices=[('A', 'Администратор'), ('U', 'Зарегистрированный пользователь'), ('M', 'Модератор')], default='U', max_length=1, verbose_name='роль'),
        ),
    ]
