# Generated by Django 3.2.12 on 2022-05-08 10:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_auto_20220508_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habruser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 10, 29, 20, 807473, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='habruser',
            name='role',
            field=models.CharField(choices=[('M', 'Модератор'), ('A', 'Администратор'), ('U', 'Зарегистрированный пользователь')], default='U', max_length=1, verbose_name='роль'),
        ),
    ]
