# Generated by Django 3.2.12 on 2022-04-13 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_alter_habruser_activation_key_expires'),
        ('authapp', '0007_auto_20220411_1332'),
    ]

    operations = [
    ]
