# Generated by Django 3.2.12 on 2022-04-25 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20220425_0200'),
        ('authapp', '0010_auto_20220422_2100'),
    ]

    operations = [
    ]
