# Generated by Django 3.2.12 on 2022-04-18 08:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_alter_habruser_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habruser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 20, 8, 45, 31, 950522, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='habruser',
            name='role',
            field=models.CharField(choices=[('A', 'Администратор'), ('M', 'Модератор'), ('U', 'Зарегистрированный пользователь')], default='U', max_length=1, verbose_name='роль'),
        ),
    ]
