# Generated by Django 3.2.12 on 2022-04-19 18:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_alter_habruser_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habruser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 18, 35, 36, 114042, tzinfo=utc)),
        ),
    ]
