# Generated by Django 3.2.12 on 2022-04-28 11:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0015_auto_20220425_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habrprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('W', 'Ж'), ('M', 'M')], max_length=1, verbose_name='пол'),
        ),
        migrations.AlterField(
            model_name='habruser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 30, 11, 47, 12, 995648, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='habruser',
            name='role',
            field=models.CharField(choices=[('A', 'Администратор'), ('M', 'Модератор'), ('U', 'Зарегистрированный пользователь')], default='U', max_length=1, verbose_name='роль'),
        ),
    ]
