# Generated by Django 3.2.12 on 2022-04-16 16:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0022_auto_20220416_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habruser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 16, 9, 49, 504853, tzinfo=utc)),
        ),
    ]
