default:
    DEBUG: false
    INSTALLED_APPS:
        - django.contrib.admin
        - django.contrib.auth
        - django.contrib.contenttypes
        - django.contrib.sessions
        - django.contrib.messages
        - django.contrib.staticfiles
development:
    ALLOWED_HOSTS:
        - '*'
    SECRET_KEY: ""
    DEBUG: true
production:
    ALLOWED_HOSTS:
        - ''
    SECRET_KEY: ""
    DEBUG: false