default:
    ALLOWED_HOSTS:
        - '*'
    DEBUG: false
    INSTALLED_APPS:
        - django.contrib.admin
        - django.contrib.auth
        - django.contrib.contenttypes
        - django.contrib.sessions
        - django.contrib.messages
        - django.contrib.staticfiles
        - mainapp
        - users
        - articleapp
    LANGUAGE_CODE: 'ru'
    TIME_ZONE: 'Europe/Moscow'
development:
    SECRET_KEY: "1"
    DEBUG: true
production:
    SECRET_KEY: "1"
    DEBUG: false
    ALLOWED_HOSTS:
        - ''