ALLOWED_HOSTS:
  - '*'
DEBUG: true
INSTALLED_APPS:
  - django.contrib.admin
  - django.contrib.auth
  - django.contrib.contenttypes
  - django.contrib.sessions
  - django.contrib.messages
  - django.contrib.staticfiles
  - social_django
  - mainapp
  - authapp
  - articleapp
  - commentapp
  - adminapp
  - ckeditor
  - news
  - searchapp
  - ratingapp
  - notificationapp

TEMPLATES:
  -
    BACKEND: 'django.template.backends.django.DjangoTemplates'
    DIRS:
      - ''
    APP_DIRS: true
    OPTIONS:
      'context_processors':
        - django.template.context_processors.debug
        - django.template.context_processors.request
        - django.contrib.auth.context_processors.auth
        - django.contrib.messages.context_processors.messages
        - mainapp.context_processor.menu_category_context

AUTHENTICATION_BACKENDS:
  - social_core.backends.google.GoogleOAuth2
  - django.contrib.auth.backends.ModelBackend
LANGUAGE_CODE: 'ru'
TIME_ZONE: 'Europe/Moscow'
AUTH_USER_MODEL: 'authapp.HabrUser'
MIDDLEWARE:
  - django.middleware.security.SecurityMiddleware
  - django.contrib.sessions.middleware.SessionMiddleware
  - django.middleware.common.CommonMiddleware
  - django.middleware.csrf.CsrfViewMiddleware
  - django.contrib.auth.middleware.AuthenticationMiddleware
  - django.contrib.messages.middleware.MessageMiddleware
  - django.middleware.clickjacking.XFrameOptionsMiddleware
  - commentapp.middleware.RequestMiddlewareUser
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: '' # Google Consumer Key
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET:  '' # Google Consumer Secret
SECRET_KEY: "1"
CKEDITOR_CONFIGS:
  'default':
    'toolbar': 'full'
    'height': '300px'
    'width': 'auto'