# Generated by Django 3.2.12 on 2022-04-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Статус активности'),
        ),
    ]
