# Generated by Django 3.2.12 on 2022-04-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentapp', '0002_auto_20220412_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_moderation',
            field=models.BooleanField(default=False, verbose_name='Модерация'),
        ),
    ]
