# Generated by Django 3.2.12 on 2022-04-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentapp', '0003_auto_20220418_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_moderation',
            field=models.BooleanField(default=True, verbose_name='Модерация'),
        ),
    ]
