# Generated by Django 3.2.12 on 2022-04-13 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentapp', '0003_alter_comments_comment_moderation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
