# Generated by Django 3.2.12 on 2022-04-14 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commentapp', '0004_alter_comments_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_articles', to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария'),
        ),
    ]
