# Generated by Django 3.2.12 on 2022-04-16 06:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commentapp', '0006_auto_20220414_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='likes',
            field=models.ManyToManyField(related_name='comments_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
