# Generated by Django 3.2.12 on 2022-04-16 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentapp', '0011_comments_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='likes',
        ),
    ]
