# Generated by Django 3.2.12 on 2022-04-16 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentapp', '0013_auto_20220416_2309'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
