# Generated by Django 3.2.12 on 2022-04-10 16:49

from django.db import migrations


def create_categories(apps, schema_editor):
    Category = apps.get_model("articleapp", "Category")
    Category.objects.create(name='Дизайн')
    Category.objects.create(name='Веб-разработка')
    Category.objects.create(name='Мобильная разработка')
    Category.objects.create(name='Маркетинг')


class Migration(migrations.Migration):
    dependencies = [
        ('articleapp', '0002_auto_20220406_1708'),
    ]

    operations = [
        migrations.RunPython(create_categories)
    ]
