# Generated by Django 3.2.12 on 2022-04-12 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0003_auto_20220410_1949'),
        ('articleapp', '0003_category_is_deleted'),
    ]

    operations = [
    ]
