# Generated by Django 3.2.12 on 2022-04-16 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0003_article_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='likes',
        ),
    ]
