# Generated by Django 3.2.12 on 2022-05-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0006_auto_20220508_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.AlterField(
            model_name='article',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='likes', to='articleapp.IpModel'),
        ),
    ]
